// Code generated by protoc-gen-go. DO NOT EDIT.
// source: news.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNewsRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNewsRequest) Reset()         { *m = GetNewsRequest{} }
func (m *GetNewsRequest) String() string { return proto.CompactTextString(m) }
func (*GetNewsRequest) ProtoMessage()    {}
func (*GetNewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0382e93bed6d84, []int{0}
}

func (m *GetNewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNewsRequest.Unmarshal(m, b)
}
func (m *GetNewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNewsRequest.Marshal(b, m, deterministic)
}
func (m *GetNewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNewsRequest.Merge(m, src)
}
func (m *GetNewsRequest) XXX_Size() int {
	return xxx_messageInfo_GetNewsRequest.Size(m)
}
func (m *GetNewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNewsRequest proto.InternalMessageInfo

func (m *GetNewsRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetNewsResponse struct {
	News                 *News    `protobuf:"bytes,1,opt,name=news,proto3" json:"news,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNewsResponse) Reset()         { *m = GetNewsResponse{} }
func (m *GetNewsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNewsResponse) ProtoMessage()    {}
func (*GetNewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0382e93bed6d84, []int{1}
}

func (m *GetNewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNewsResponse.Unmarshal(m, b)
}
func (m *GetNewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNewsResponse.Marshal(b, m, deterministic)
}
func (m *GetNewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNewsResponse.Merge(m, src)
}
func (m *GetNewsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNewsResponse.Size(m)
}
func (m *GetNewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNewsResponse proto.InternalMessageInfo

func (m *GetNewsResponse) GetNews() *News {
	if m != nil {
		return m.News
	}
	return nil
}

func (m *GetNewsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type News struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Header               string   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *News) Reset()         { *m = News{} }
func (m *News) String() string { return proto.CompactTextString(m) }
func (*News) ProtoMessage()    {}
func (*News) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0382e93bed6d84, []int{2}
}

func (m *News) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_News.Unmarshal(m, b)
}
func (m *News) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_News.Marshal(b, m, deterministic)
}
func (m *News) XXX_Merge(src proto.Message) {
	xxx_messageInfo_News.Merge(m, src)
}
func (m *News) XXX_Size() int {
	return xxx_messageInfo_News.Size(m)
}
func (m *News) XXX_DiscardUnknown() {
	xxx_messageInfo_News.DiscardUnknown(m)
}

var xxx_messageInfo_News proto.InternalMessageInfo

func (m *News) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *News) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *News) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type Error struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0382e93bed6d84, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNewsRequest)(nil), "GetNewsRequest")
	proto.RegisterType((*GetNewsResponse)(nil), "GetNewsResponse")
	proto.RegisterType((*News)(nil), "News")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("news.proto", fileDescriptor_2c0382e93bed6d84) }

var fileDescriptor_2c0382e93bed6d84 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xbd, 0xaa, 0xc2, 0x30,
	0x14, 0xc7, 0x69, 0x9a, 0xf6, 0x72, 0xcf, 0x85, 0x5e, 0xc8, 0x20, 0x11, 0x1c, 0x4a, 0x26, 0xa7,
	0x0e, 0x8a, 0x2f, 0x50, 0x10, 0xc1, 0xc1, 0x21, 0xa3, 0x5b, 0x6b, 0x0e, 0xda, 0xc1, 0xa6, 0x26,
	0x91, 0xbe, 0xbe, 0xe4, 0xb4, 0x3a, 0xb8, 0xfd, 0xbf, 0xf2, 0x0b, 0x07, 0xa0, 0xc7, 0xd1, 0x57,
	0x83, 0xb3, 0xc1, 0xaa, 0x12, 0x8a, 0x03, 0x86, 0x13, 0x8e, 0x5e, 0xe3, 0xe3, 0x89, 0x3e, 0x88,
	0x02, 0x58, 0x67, 0x64, 0x52, 0x26, 0xeb, 0x54, 0xb3, 0xce, 0xa8, 0x23, 0xfc, 0x7f, 0x16, 0x7e,
	0xb0, 0xbd, 0x47, 0xb1, 0x04, 0x1e, 0x11, 0x34, 0xfa, 0xdb, 0x64, 0x15, 0x95, 0x14, 0x89, 0x15,
	0x64, 0xe8, 0x9c, 0x75, 0x92, 0x51, 0x97, 0x57, 0xfb, 0xe8, 0xf4, 0x14, 0xaa, 0x1a, 0x78, 0xdc,
	0x7e, 0xff, 0x21, 0x16, 0x90, 0xdf, 0xb0, 0x31, 0x38, 0x3d, 0xfb, 0xd5, 0xb3, 0x13, 0x02, 0xb8,
	0x69, 0x02, 0xca, 0x94, 0x52, 0xd2, 0x6a, 0x07, 0x19, 0x31, 0x63, 0x79, 0xb1, 0x06, 0x67, 0x0c,
	0x69, 0x21, 0xe1, 0xe7, 0x8e, 0xde, 0x37, 0x57, 0x9c, 0x49, 0x6f, 0x5b, 0xf3, 0x33, 0x1b, 0xda,
	0x36, 0xa7, 0xab, 0xb7, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0x8f, 0xea, 0x14, 0x03, 0x01,
	0x00, 0x00,
}
